POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "dani223",
    "nombres": "Daniela",
    "apellidos": "Salazar",
    "correo": "daniela123@correo.com",
    "password": "Daniela123-"
}