POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "Andrea03",
    "nombres": "Monica Andrea",
    "apellidos": "Salazar Mosquera",
    "correo": "Monica23@correo.com",
    "password": "AndreaS123-"
}